config/routes.rb
Rails.application.routes.draw do
  root 'characters#new'
  resources :characters
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :st, :dx, :iq, :ht, presence: true

  attr_accessor :character_datum

  def gurps_character
    @gurps_character ||= build_gurps_character
  end

private

  def build_gurps_character
    char = Gurps::Character.new
    char.strength = st
    char.dexterity = dx
    char.intelligence = iq
    char.health = ht
    char
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    @character = Character.find(params[:id])
    @gurps_character = @character.gurps_character
  end

  def new
    @character = Character.new
  end

  def create
    character = Character.create!(character_params)
    redirect_to character_path(character)
  end

  def update
    character = Character.find(params[:id])
    character.update_attributes! character_params
    redirect_to character_path(character)
  end

  private

  def character_params
    params.require(:character).permit(:name, :st, :dx, :iq, :ht)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gurps_attributes
     %w[lifting basic_lift thrust_damage swing_damage damage weight hit_points will perception fatigue
        basic_speed dodge basic_move move encumbrance_level]
  end
end

app/views/characters/_form.haml
.row
  %nav.navbar.navbar-default{role: 'navigation'}
    = simple_form_for @character, html: { class: 'navbar-form navbar-left' } do |f|
      = f.input :name, :input_html => { :class => 'span3' }
      = f.input :st, :input_html => { :class => 'span3' }
      = f.input :dx, :input_html => { :class => 'span3' }
      = f.input :iq, :input_html => { :class => 'span3' }
      = f.input :ht, :input_html => { :class => 'span3' }
      = f.button :submit

app/views/characters/new.html.haml
.row
  .col-md-2
    = render :partial => 'form'

  .col-md-10
    %h1 Welcome to Uplift!

app/views/characters/show.html.haml
.row
  .col-md-2
    = render :partial => 'form'

  .col-md-10
    - gurps_attributes.each do |field|
      .field
        = "#{field.humanize}: #{@gurps_character.public_send(field)}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <title>Uplift</title>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Uplift', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active dropdown">
          <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
            Characters
            <b class='caret'></b>
          </a>

          <ul class="dropdown-menu">
            <li><%= link_to 'List all characters', characters_path %></li>
            <li><%= link_to 'New character', new_character_path %></li>
          </ul>
        </li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</header>

<div class="container master-container">
  <% if notice %>
    <div class="alert alert-success fade in" data-alert="alert">
      <a class="close" data-dismiss='alert' href="#">×</a>
      <p><%= notice %></p>
    </div>
  <% end %>

  <%= yield %>
</div>

<footer class="footer">
  <div class="container">
    <p>Copyright 2013-2014 <a href="http://dimascyriaco.com.br">Dimas Cyriaco </a></p>

    <ul class="footer-links">
      <li><a href="https://github.com/dimascyriaco">Dimas Cyriaco @ GitHub</a></li>
    </ul>
  </div>
</footer>

<%= javascript_include_tag 'application' %>
</body>
</html>